{"uid":"6ca81335902b3557","name":"Fail Test","fullName":"User Login to katalon-demo-cura application: Fail Test","historyId":"d3d39de6fc3cd407f5d66e2d343702f9","time":{"start":1727096412363,"stop":1727096412594,"duration":231},"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","steps":[{"name":"Given I am failure","time":{"start":1727096412363,"stop":1727096412594,"duration":231},"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","steps":[],"attachments":[{"uid":"594250aabab09ee7","name":"I_am_failure_failed.png","source":"594250aabab09ee7.png","type":"image/png","size":1227888}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"User Login to katalon-demo-cura application"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"6ca81335902b3557.json","parameterValues":[]}