{"uid":"c38f3ccaf84da03","name":"Fail Test","fullName":"User Login to katalon-demo-cura application: Fail Test","historyId":"d3d39de6fc3cd407f5d66e2d343702f9","time":{"start":1727100416005,"stop":1727100416008,"duration":3},"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":9,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","steps":[{"name":"Given I am failure","time":{"start":1727100416005,"stop":1727100416008,"duration":3},"status":"broken","statusMessage":"KeyError: 'url'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"User Login to katalon-demo-cura application"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"f170e20f1a9d6a3d","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727100198562,"stop":1727100198565,"duration":3}},{"uid":"830c5e7489d7ae36","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727098983374,"stop":1727098983376,"duration":2}},{"uid":"e98e2c27c938197c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=48239): Max retries exceeded with url: /session/182ed2b93db7bbf3748c69ce5ef84bff/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2822a62af0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n","time":{"start":1727098643488,"stop":1727098643491,"duration":3}},{"uid":"97391daf98b829bb","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727098365661,"stop":1727098365901,"duration":240}},{"uid":"6ca81335902b3557","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727096412363,"stop":1727096412594,"duration":231}},{"uid":"2d967866af8a70a","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727095943503,"stop":1727095943504,"duration":1}},{"uid":"b48dc314f7b675bb","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727095633799,"stop":1727095633800,"duration":1}},{"uid":"954b712559bde10","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727095486616,"stop":1727095486617,"duration":1}},{"uid":"e2ce5585e2b26460","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727095073474,"stop":1727095073475,"duration":1}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"be766a8385d52b1c","status":"broken","statusDetails":"KeyError: 'url'\n","time":{"start":1727095073474,"stop":1727095073475,"duration":1}}]},"tags":[]},"source":"c38f3ccaf84da03.json","parameterValues":[]}