{"name": "Fail Test", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "steps": [{"name": "Given I am failure", "status": "broken", "statusDetails": {"message": "KeyError: 'url'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 191, in impl\n    with StepContext(self.title.format(*args, **params), params):\n"}, "start": 1727095486616, "stop": 1727095486617}], "start": 1727095486616, "stop": 1727095486617, "uuid": "d14a2439-4f1a-4eea-b896-0e2c6a1cc398", "historyId": "d3d39de6fc3cd407f5d66e2d343702f9", "fullName": "User Login to katalon-demo-cura application: Fail Test", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login to katalon-demo-cura application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}